Added optional dst_res parameter to reproject
aeronetlab/aeronetlib pull request #36
Opened 2022-04-01 12:48 UTC by hfmuzb

2022-04-03 11:50 UTC, AlexeyTrekin requested changes
278: Default value should not change the previous behavior by default, meaning that all calls without this parameter should return the same results as before.

As far as we pass this value to rasterio.warp functions calculate_default_transform and reproject, it should follow their default value (None). In this case, if we do not specify dst_res, it will be passed as None which is the same as not passing it.

315-318: It is better to use 'resolution' parameter in calculate_default_transform to get the output shape, not multiply the shape afterwards.

See https://rasterio.readthedocs.io/en/latest/api/rasterio.warp.html#rasterio.warp.calculate_default_transform

2022-04-03 11:50 UTC, AlexeyTrekin commented on aeronet/dataset/raster/band.py
> +        width = round(width / (dst_res[0]/self.res[0]))
It is better to use 'resolution' parameter in calculate_default_transform to get the output shape, not multiply the shape afterwards.

See https://rasterio.readthedocs.io/en/latest/api/rasterio.warp.html#rasterio.warp.calculate_default_transform

2022-04-03 11:50 UTC, AlexeyTrekin commented on aeronet/dataset/raster/band.py
> +    def reproject(self, dst_crs, dst_res=(1, 1), fp=None, interpolation='nearest'):
Default value should not change the previous behavior by default, meaning that all calls without this parameter should return the same results as before.

As far as we pass this value to rasterio.warp functions calculate_default_transform and reproject, it should follow their default value (None). In this case, if we do not specify dst_res, it will be passed as None which is the same as not passing it.

2022-04-04 07:14 UTC, hfmuzb commented
Applied requested changes.
278: Default value of dst_res=None 
313: Add 'resolution' parameter to calculate_default_transform to get the output shape

2022-04-04 09:46 UTC, AlexeyTrekin reviewed
OK, great! Now let's add new parameter and description to docstrings, and make sure it is tested.

2022-04-04 09:49 UTC, AlexeyTrekin approved these changes

2022-04-05 11:04 UTC, merged